fix for 4diau with iau_filter_increments=T
NOAA-GFDL/GFDL_atmos_cubed_sphere pull request #167
Opened 2022-01-04 16:36 UTC by jswhit

**Description**

This PR fixes a bug in the 4DIAU code when the parameter iau_filter_increments=T.  The time bounds for the IAU interval were computed incorrectly, leading to incorrect filter weights that were applied outside the designated time range.   The 4DIAU with constant weights, and 3DIAU (with a single increment file specified) were not affected by this bug.

Fixes https://github.com/ufs-community/ufs-weather-model/issues/989

**How Has This Been Tested?**

Regression tests pass on hera, cycling DA experiment with iau_filter_increments=T and hourly increment files ran on orion.

**Checklist:**

Please check all whether they apply or not
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-09 03:16 UTC, MingjingTong-NOAA requested changes
I tested the changes for both 4DIAU and 3DIAU. The fix works for 4DIAU, but not for 3DIAU. When running 3DIAU, nfiles = 1 and IPD_Control%iaufhrs(1) = IPD_Control%iaufhrs(nfiles). The 'if' condition in line 318 is never satisfied (iau_state%wt is always 0), and the if condition in line 336 is always satisfied (IAU_Data%in_interval is always false).

2022-01-13 17:27 UTC, MingjingTong-NOAA commented
The new changes works for 3DIAU now, but not 4DIAU. The problem is the change in line 357. The t2 here has different meaning. It's no longer IPD_Control%iaufhrs(nfiles). If reverting the change of line 357, it works for 4DIAU. 

I have another recommendation for 3DIAU. Please consider removing the 'if' condition 'if (IPD_Control%iau_filter_increments) ' in line 348. Otherwise, if iau_filter_increments = .false., setiauforcing will not be called, the iau increment will not be normalized by rdt.

2022-01-13 17:32 UTC, MingjingTong-NOAA requested changes
The new changes works for 3DIAU now, but not 4DIAU. The problem is the change in line 357. The t2 here has different meaning. It's no longer IPD_Control%iaufhrs(nfiles). If reverting the change of line 357, it works for 4DIAU.

I have another recommendation for 3DIAU. Please consider removing the 'if' condition 'if (IPD_Control%iau_filter_increments) ' in line 348. Otherwise, if iau_filter_increments = .false., setiauforcing will not be called, the iau increment will not be normalized by rdt.

2022-01-13 19:46 UTC, MingjingTong-NOAA commented
Please ignore my second recommendation. I saw that setiauforcing is called in IAU_initialize.

2022-01-28 14:54 UTC, laurenchilutti commented
@MingjingTong-NOAA do you think this PR is acceptable or do you still think there are changes that should be made?

2022-02-01 03:35 UTC, jswhit commented
@MingjingTong-NOAA thanks for reviewing this. I see the problem you found is related to the variable t2 being redefined.  Instead of your suggested fix (which would have worked fine) I created a different variable tnext and preserved the t2 variable to use in the if test.  4DIAU should work now.

2022-02-01 17:23 UTC, MingjingTong-NOAA commented
The fix looks fine to me. The pull request can be merged. Thanks!

2022-02-02 15:17 UTC, bensonr approved these changes

2022-02-04 13:31 UTC, junwang-noaa commented
@laurenchilutti @bensonr All the RT passed in ufs-weather-model [PR#990](https://github.com/ufs-community/ufs-weather-model/pull/990), would you please commit this PR? Thanks

2022-02-04 15:56 UTC, laurenchilutti approved these changes

2022-02-04 15:56 UTC, merged